### ISSUE TITLE
Math expression 

### ISSUE THREAD

**Issue by shd101wyy** [cyrilis/epub-gen#20]
Hi, 

Thanks for this awesome library.

Is there a way to include math rendering like [MathJax](https://github.com/mathjax/MathJax) or [KaTeX](https://github.com/Khan/KaTeX) inside the generated epub file?

Thanks ;)

**Comment by cyrilis** [comment]
Hi @shd101wyy ,

MathJax and KaTeX are js libraries for rendering math typesetting into HTML(SVG). if you want to render typesettings real-time in epub readers, there are few ebook readers to choose from, as ebook readers need to be able to execute javascript. 

However, I think you can firstly render math typesettings into HTML(SVG), then generate the epub file with the generated HTML(SVG) string via epub-gen, **you can get generated HTML(SVG) with Phantomjs or some other library programmatically**. Then you will get a ebook file which is available for almost all ebook reader.

Hope this helps.

**Comment by shd101wyy** [comment]
Thanks for your reply.

I am now trying to convert a html file to epub.
The html file is attached [test.html.zip](https://github.com/cyrilis/epub-gen/files/386416/test.html.zip).

It seems that css like `.markdown-preview-enhanced[data-use-github-style]` that ends with attribute does not work correctly.

Also, SVG graph is failed to be rendered.

**Comment by pedrosanta** [comment]
Hi @shd101wyy,

Code/scripts I only think they would work for EPUB 3, and there may be a good bunch of restrictions - also I think there's the best practice of the book to provide content for readers that don't support scripting.

More info at:
* http://www.idpf.org/epub/30/spec/epub30-contentdocs.html#sec-scripted-content
* https://idpf.github.io/a11y-guidelines/content/script/pe.html
* http://epubzone.org/news/epub-3-and-interactivity

But, it seems to me that, the best way to have _math_ on an EPUB is really to use MathML.

You can see more information about MathML on EPUB 3 here: http://www.idpf.org/epub/30/spec/epub30-contentdocs.html#sec-xhtml-mathml

Also, I just noticed on the MathJax documentation that a good amount of EPUB readers use it to render MathML: http://docs.mathjax.org/en/latest/misc/epub.html

Seems to me that MathML is the way to go regarding math on EPUB. 🙂

Cheers!

**Comment by shd101wyy** [comment]
Hi @pedrosanta ,

Thank you very much for your advice and I will have a look into the MathML :)
