### ISSUE TITLE
Chapter discontinued after first image

### ISSUE THREAD

**Issue by peternerlich** [cyrilis/epub-gen#25]
I am trying to make a comic epub out of scanned pages. A chapter consists of many images acting as one page. I have tried to display them like so:

    <img src="file:///path/to.file1" /><img src="file:///path/to.file2" /><img src=...

or:

    <img src="file:///path/to.file1" /><br />
    <img src="file:///path/to.file2" /><br />
    <img src=...

But somehow only the code until and including the first image makes it into the epub file.

**Comment by cyrilis** [comment]
Hi @peternerlich , 

I made a local test, but it seems ok, I can see all images in the chapter. 
and my test data is: 

```html
      <img src="file:///Users/Cyril/Downloads/photo-1462774603919-1d8087e62cad.jpeg" /> <br/>
      <img src="file:///Users/Cyril/Downloads/preview.gif" /> <br/>
      <img src="file:///Users/Cyril/Downloads/preview.jpg" /> <br/>
      <img src="file:///Users/Cyril/Downloads/tabbar-style.gif" /> <br/>
```
Could you show me the raw data of your option and upload the generated epub file so we can inspect?

**Comment by cyrilis** [comment]
Hi @peternerlich ,

I found out that if img tag is not closed, it will cause img tag only read first if cheerio lib read in xml mode. You can wait for out next release to fix this problem or just change 
`<img src="file:///.../001.png">` 
into 
`<img src="file:///.../001.png"/>` to fix this. 

Thanks 😃

**Comment by pedrosanta** [comment]
Hi @peternerlich, I've just updated the library to [`0.0.15`](https://github.com/cyrilis/epub-gen/releases/tag/v0.0.15) which will fix that issue you're having. Just update and it should work now. Closing this one.

Cheers.
