### ISSUE TITLE
Books without images give warning on EPUB check/validator

### ISSUE THREAD

**Issue by pedrosanta** [cyrilis/epub-gen#27]
So, bumped into this issue, when you have a book with no images, it throws a warning complaining about the images directory being empty, as such:

![screen shot 2016-08-02 at 15 45 59](https://cloud.githubusercontent.com/assets/2737/17332916/59e7c900-58c8-11e6-884f-4c06e8f5e179.png)

We need to make this directory creation dependent of having images or not - perhaps move the create dir code to the download images method or so.

Anyway, putting this in as a note.

**Comment by cyrilis** [comment]
Hi @pedrosanta ,

I made a little change, if no images in the book, the image directory will not created.

**Comment by pedrosanta** [comment]
Well this will make @matthewcobb happy. 👌
