### ISSUE TITLE
Not working with Grunt

### ISSUE THREAD

**Issue by timtribers** [cyrilis/epub-gen#30]
Hi Guys,

Thanks for producing this package.

I'm trying to run this under Grunt, as part of an automated publication platform, but getting no output generated.  Specifically:
- it installs ok
- it creates node-modules/epub-gen/tempDir/{uuid} ok
- it creates files in that temp dir ok, and they all look as expected
- it creates (opens) an output epub file
- but there it finishes - no errors - no content in the epub (0 bytes)
- last console output is 'Zipping temp dir to . . . .' - as expected - but no 'Done zipping' message

If I step into the node-modules/epub-gen folder and run npm test, I get all the console messages (right through to 'Done') and good output generated.

I have logged cwd, option.output and the archive and output (fs) objects all the way through good (npm) and bad (grunt) runs, and there is no difference.  :(

I have tried it on Windows and Ubuntu with exactly the same results.

Have to say, I'm stumped.

Any ideas?

**Comment by cyrilis** [comment]
Hi, @timtribers 
Could you provide the script or configuration you run with grunt? 
Thanks.

**Comment by timtribers** [comment]
Hi @cyrilis 

Actually, think I might just have worked out the problem . . .

Grunt tasks are synchronous by default, so wrapping epub-gen is fine, up until it hits some async stuff such as using fs to write a file.

There is a way to flag to make a Grunt task async - will try that.

Thx

**Comment by cyrilis** [comment]
@timtribers 
You can try:
```javascript
    new Epub(option [, output]).promise.then(function(){
        console.log("Ebook Generated Successfully!")
    }, function(err){
        console.error("Failed to generate Ebook because of ", err)
    })
```
for asynchronous usage.

cheers.

**Comment by timtribers** [comment]
Yay, that was the problem - should have guessed sooner.

Here's how to wrap in Grunt, for anyone coming to this in the future . . .

```
  // Custom task to write epub file
  grunt.registerTask('epubGen', function(){
    var done = this.async();
    var Epub = require("epub-gen");
    ...
    new Epub(option [, output]).promise.then(function(){
        console.log("Ebook Generated Successfully!")
        done();
    }, function(err){
        console.error("Failed to generate Ebook because of ", err)
        done(err);
    });
   });
```

Sorry to have raised an issue.

Thx for a great library.

**Comment by timtribers** [comment]
**Postscript**
After using the above for around a month, I was still getting random times when the produced epub file was corrupted and unreadable.  I spent a frustrating day trying to debug the problem, and eventually concluded that it was another timing issue.

It's crude, but the only way I found to make it go away altogether was to amend the code immediately above to replace:
`        done();`
with:
`        setTimeout(function(){done();}, 1000);`

Hope that helps someone.

**Comment by deanebarker** [comment]
@timtribers 

>Hope that helps someone.

You're damn right it did.  If you were standing here, I'd kiss you.

This is also relevant:

https://github.com/gruntjs/grunt/issues/1531#issuecomment-232101287

You cannot use `this.async()` this if you use the fancy "fat arrow" syntax:

```
grunt.registerTask('build', 'Make the EPUB', () => { ... }
```

You have to do the old school syntax:

```
grunt.registerTask('build', 'Make the EPUB', function() { ... }
```
