### ISSUE TITLE
FEATURE: Add optional filename

### ISSUE THREAD

**Issue by timtribers** [cyrilis/epub-gen#32]
Hi,

How about the ability to specify a filename for each content item, e.g.:

```
content: [
            {
                title: "Down the Rabbit Hole",
                data: "<p>Alice was beginning to get very tired...</p>",
                filename: "chapter2"
            }

```

Why?  Because its very hard to construct <a> links in the markup that point to other content if you do not know the relevant filename.

(I know, I can work it out from counting the place in the content array and concatenating the title, but that doesn't seem very robust)

Thx.

**Comment by cyrilis** [comment]
Hi @timtribers ,

You can specify filename of each chapter now, but please note that  if your filename is not end with `.xhtml`, we will add `.xhtml` to the end of the filename you provided.

🚀

**Comment by pedrosanta** [comment]
Yep, I also had the need to do this and counting the place in the content and concatenating the title/slug was precisely what I did to have cross-content references and links.

But yhea, I agree a `filename` content option to be more simple and useful. 👍
