### ISSUE TITLE
Could not download images

### ISSUE THREAD

**Issue by gfd6th** [cyrilis/epub-gen#36]
I find that the epub book works fine in ibooks osx. 
But if I transfer this book to ipad by Airdrop and open it with ibooks App, the images all gone.

I try unzip the epub, there are nothing image files.

**Comment by pedrosanta** [comment]
Hi @gfd6th, I think we have an issue with images downloads with the latest version. I will submit a fix for that soon, meanwhile is it possible to use the `0.0.16` version?

Cheers.

**Comment by gfd6th** [comment]
Thanks for your awesome script, I'm backward to 0.0.16 now. That works

**Comment by pedrosanta** [comment]
I'll be re-opening this as the issue persists on latest version.

**Comment by afram** [comment]
Cheerio doesn't like encodeXML...

**Comment by pedrosanta** [comment]
Version [v0.0.18](https://github.com/cyrilis/epub-gen/releases/tag/v0.0.18) was just released with this fixed.
