### ISSUE TITLE
mimetype is empty

### ISSUE THREAD

**Issue by dehlen** [cyrilis/epub-gen#43]
Mimetype file is always empty for the generated epub. Excatly this means the file is there in the epub archive but the file is 0 bytes in size and does not have the application/epub+zip string in it.

**Comment by dehlen** [comment]
I found a fix by replacing `archive.file(cwd + "/mimetype", ...) `with `archive.append("application/epub+zip", {name: "mimetype, ...})`

However I am not sure why archive.file does not work as expected here since the mimetype file is correctly created in the tmpDir. 

Closing this as of now I got a fix.

**Comment by dehlen** [comment]
Just letting you know that i made a PR regarding this issue :  #44.

**Comment by pedrosanta** [comment]
Weird @dehlen, my `mimetype` file over here was ok before and after #44. 🤔

Anyway, appending from string like you added on #44 might be simpler, more readable. 👍
