### ISSUE TITLE
“Namespace prefix epub for type on a is not defined”

### ISSUE THREAD

**Issue by actuallymentor** [cyrilis/epub-gen#47]
Hello,

I am trying to use the EPUB3 provision for footnote popups by adding ```epub:type="noteref"``` to my footnote declarations.

In ibooks this results in the error in the title (screenshot attached).

I can see in your lib that you declare ```xmlns:epub=”http://www.idpf.org/2007/ops”``` which should make iBooks respect the epub namespace. I've inspected the epub itself and found the markup to indeed include ```xmlns:epub=http://www.idpf.org/2007/ops```.

I did notice that ```http://www.idpf.org/2007/ops``` gives a 404. If this is an issue the link in your code should be update to whatever is the current live link.

I am using version 0.0.17 with ``` { version: 3 } ```.

If you have any idea how to debug this it would be most welcome.

**Comment by pedrosanta** [comment]
Hi @actuallymentor, just merged #67 that will allow to properly user those attributes.

Just checked out and that [`http://www.idpf.org/2007/ops` is **indeed** the correct URI for the spec](http://www.idpf.org/epub/30/spec/epub30-contentdocs.html#sec-overview-nspfx) and that it doesn't need to **explicitly** resolve to a page, it's just an identifier – which for me also sounds dumb, but, W3C XML computers overall weirdness I guess. 🤷‍♂️
