### ISSUE TITLE
Generation fails when deployed to Heroku

### ISSUE THREAD

**Issue by andreathniah** [cyrilis/epub-gen#65]
Hey, thank you for this neat library. While it works perfectly locally, I seem to have trouble generating epub file when my application is deployed to Heroku.

It seems to always generate the following error code:
```
Generating Template Files.....
Downloading Images...
Making Cover...
Generating Epub Files...
Zipping temp dir to archive/test.epub
events.js:183
	throw er; // Unhandled 'error' event
	^
```

Here's the little snippet that I used:
``` javascript
app.post("/epub", (req, res) => {
  let epubURL = req.body.url;
  let epubTitle = req.body.title;
  let epubAuthor = req.body.author;
  let epubSummary = req.body.summary;
  let epubContent = req.body.content;

  const fileName = `archive/${epubTitle}.epub`;
  const option = {
    title: epubTitle,
    author: epubAuthor, 
    content: [{ data: epubSummary }, { data: epubContent }]
  };

  new Epub(option, fileName).promise
    .then(() => {
      console.log("[#] Success => Id: ", epubURL, "\n");
      const file = __dirname + `/${fileName}`;
      res.download(file);
    })
    .catch(err => {
      console.log(err);
    });
});
```

Any help would be appreciated.

**Comment by cyrilis** [comment]
Hi @andreathniah 

Without the detail error stack trace, I can only guess it maybe caused by `archive` directory permission or existence. Can you provide detail error message so that we can dig into this issue?

**Comment by andreathniah** [comment]
Thank you for the fast reply @cyrilis 

It was indeed an error caused by `archive` directory existence. Epub-gen is working fine now. 
Thank you for pointing me to the right direction!
