### ISSUE TITLE
Handle images which starts with relative path

### ISSUE THREAD

**Issue by sivagao** [cyrilis/epub-gen#70]
if the html's image src attribute is relative path.(the image file exists relative to html file). in this case, the image won't be included by fs copy

**Comment by cyrilis** [comment]
Hi @sivagao ,

This library accept html source as string, so we can't detect the real path of the images with relative path. 

However this library can process two kind of image resource: 

- remote image url start with `http[s]://` 
- local image file path start with `file://...`  

I recommend to preprocess the html content string and alter your image src attributes like `../static/images1.png` into like `file:///usr/local/share/download/temp-epub/static/images1.png`, so this `epub-gen` library could locate the real image file path.

Hope this helps 😄

**Comment by cyrilis** [comment]
Closing for now.  If you have any question, please reopen again.
