### ISSUE TITLE
Missing Hard timeout & Retry mechanism when downloading images.

### ISSUE THREAD

**Issue by gonejack** [cyrilis/epub-gen#71]
Thanks to author, I made a daemon thanks to the epub-gen, but it could hangs forever frequently when downloading images with pool network connection condition by await (new Epub(option, path).promise).

With quick browsing to related code, epub-gen seems missing hard timeout when piping streams, could you please solving it author?

**Comment by cyrilis** [comment]
Hi @gonejack ,

Currently this library doesn't handle image downloading progress properly. But you can download images into temporary directory then reference images onto these local images to avoid network issue or unexpected hanging. 

See similar issue here:  https://github.com/cyrilis/epub-gen/issues/66 

Hope this helps.

**Comment by cyrilis** [comment]
I'm closing for now, if you have further questions, please reopen it or create a new issue.
