### ISSUE TITLE
zip command not running in quiet mode

### ISSUE THREAD

**Issue by grawlinson** [cyrilis/epub-gen#8]
Whenever an EPUB is generated, the zip command spits out a lot of information to the console.

For example:

```

  adding: mimetype (stored 0%)

  adding: META-INF/ (stored 0%)
  adding: META-INF/container.xml (deflated 30%)
  adding: OEBPS/ (stored 0%)
  adding: OEBPS/<each chapter>.html (deflated 62%)


```

When generating multiple EPUB files, it would be beneficial if this output was suppressed.

**Comment by cyrilis** [comment]
Fixed in #9
